'use strict';

export const WEB_AUTHENTICATION = 'WEB_AUTHENTICATION';
export const WEB_NETWORK_ERROR = 'WEB_NETWORK_ERROR';
export const WEB_START_CONFIG = 'WEB_START_CONFIG';
export const APP_CONFIG = 'APP_CONFIG';
export const APP_USER_CONFIG = 'APP_USER_CONFIG';
export const CLOSE_UPDATE_MODAL = 'CLOSE_UPDATE_MODAL';
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL';
export const CLICK_BACK_PAGE = 'CLICK_BACK_PAGE';

export const SET_SEARCH_HISTORY_KEY = 'SET_SEARCH_HISTORY_KEY';
export const GET_SEARCH_HISTORY = 'GET_SEARCH_HISTORY';
export const ADD_LIST_SEARCH_HISTORY = 'ADD_LIST_SEARCH_HISTORY';
export const ADD_INPUT_SEARCH_HISTORY = 'ADD_INPUT_SEARCH_HISTORY';
export const CLEAR_LIST_SEARCH_HISTORY = 'CLEAR_LIST_SEARCH_HISTORY';
export const CLEAR_INPUT_SEARCH_HISTORY = 'CLEAR_INPUT_SEARCH_HISTORY';

export const FORBIDDEN_TAB_CHANGED = 'FORBIDDEN_TAB_CHANGED';

export const APP_LOADING_CHANGED = 'APP_LOADING_CHANGED';

export const APP_NETWORK_CHANGED = 'APP_NETWORK_CHANGED';
export const APP_SIGNIN_CHANGED = 'APP_SIGNIN_CHANGED';
export const MESSAGE_NOTICE_GETED = 'MESSAGE_NOTICE_GETED';
export const MESSAGE_NOTICE_VISIBLE_CHANGED = 'MESSAGE_NOTICE_VISIBLE_CHANGED';
export const FORCE_UPDATE_GETED = 'FORCE_UPDATE_GETED';

export const LEVEL_PUSHED = 'LEVEL_PUSHED';
export const NEW_LEVEL_MODAL_CHANGED = 'NEW_LEVEL_MODAL_CHANGED';

export const VERIFIED_NOTICE_SET = 'VERIFIED_NOTICE_SET';
export const VERIFIED_NOTICE_VISIBLE_CHANGED = 'VERIFIED_NOTICE_VISIBLE_CHANGED';

export const VERIFIED_RESULT_SET = 'VERIFIED_RESULT_SET';
export const VERIFIED_RESULT_VISIBLE_CHANGED = 'VERIFIED_RESULT_VISIBLE_CHANGED';