'use strict';

export const WEB_AUTHENTICATION = 'WEB_AUTHENTICATION';
export const WEB_NETWORK_ERROR = 'WEB_NETWORK_ERROR';
export const WEB_START_CONFIG = 'WEB_START_CONFIG';
export const APP_CONFIG = 'APP_CONFIG';
export const CLOSE_UPDATE_MODAL = 'CLOSE_UPDATE_MODAL';
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL';
export const CLICK_BACK_PAGE = 'CLICK_BACK_PAGE';

export const SET_SEARCH_HISTORY_KEY = 'SET_SEARCH_HISTORY_KEY';
export const GET_SEARCH_HISTORY = 'GET_SEARCH_HISTORY';
export const ADD_LIST_SEARCH_HISTORY = 'ADD_LIST_SEARCH_HISTORY';
export const ADD_INPUT_SEARCH_HISTORY = 'ADD_INPUT_SEARCH_HISTORY';
export const CLEAR_LIST_SEARCH_HISTORY = 'CLEAR_LIST_SEARCH_HISTORY';
export const CLEAR_INPUT_SEARCH_HISTORY = 'CLEAR_INPUT_SEARCH_HISTORY';

export const FORBIDDEN_TAB_CHANGED = 'FORBIDDEN_TAB_CHANGED';

export const APP_LOADING_CHANGED = 'APP_LOADING_CHANGED';