'use strict';

export const WEB_AUTHENTICATION = 'WEB_AUTHENTICATION';
export const WEB_NETWORK_ERROR = 'WEB_NETWORK_ERROR';
export const WEB_START_CONFIG = 'WEB_START_CONFIG';
export const APP_CONFIG = 'APP_CONFIG';
export const CLOSE_UPDATE_MODAL = 'CLOSE_UPDATE_MODAL';
export const CLICK_BACK_PAGE = 'CLICK_BACK_PAGE';