'use strict';

export const ATTENTION_BLOCK_SET_FETCHED = 'ATTENTION_BLOCK_SET_FETCHED';
export const ATTENTION_BLOCK_SET_ADDED = 'ATTENTION_BLOCK_SET_ADDED';
export const ATTENTION_BLOCK_SET_DELETED = 'ATTENTION_BLOCK_SET_DELETED';
export const ATTENTION_BLOCK_SET_CLEAR = 'ATTENTION_BLOCK_SET_CLEAR';
export const ATTENTION_BLOCK_SET_ENTERED = 'ATTENTION_BLOCK_SET_ENTERED';

export const CITY_LIST_FETCHED = 'CITY_LIST_FETCHED';
export const CUR_CITY_CHANGED = 'CUR_CITY_CHANGED';