'use strict';

export const ATTENTION_BLOCK_SET_FETCHED = 'ATTENTION_BLOCK_SET_FETCHED';
export const ATTENTION_BLOCK_SET_ADDED = 'ATTENTION_BLOCK_SET_ADDED';
export const ATTENTION_BLOCK_SET_DELETED = 'ATTENTION_BLOCK_SET_DELETED';
export const ATTENTION_BLOCK_SET_CLEAR = 'ATTENTION_BLOCK_SET_CLEAR';

