'use strict';

export const ATTENTION_LIST_ONE_SET_FETCHED = 'ATTENTION_LIST_ONE_SET_FETCHED';
export const ATTENTION_LIST_ONE_BLOCK_CHANGED = 'ATTENTION_LIST_ONE_BLOCK_CHANGED';
export const ATTENTION_LIST_ONE_COMMUNITY_ROMOVED = 'ATTENTION_LIST_ONE_COMMUNITY_ROMOVED';
export const ATTENTION_LIST_ONE_COMMUNITY_CHANGED = 'ATTENTION_LIST_ONE_COMMUNITY_CHANGED';
