export const REAL_NAME_CHANGED = 'REAL_NAME_CHANGED';
export const ID_CARD_NUM_CHANGED = 'ID_CARD_NUM_CHANGED';
export const WORK_ADDRESS_CHANGED = 'WORK_ADDRESS_CHANGED';
export const BUSINESS_CARD_CHANGED = 'BUSINESS_CARD_CHANGED';
export const IDENTITY_CARD_CHANGED = 'IDENTITY_CARD_CHANGED';
