export const ALIPAY_NAME_CHANGED = 'ALIPAY_NAME_CHANGED';
export const BIND_STEP_CHANGED = 'BIND_STEP_CHANGED';
export const ALIPAY_ERR_MSG = 'ALIPAY_ERR_MSG';
export const ALIPAY_FETCHED = 'ALIPAY_FETCHED';
