'use strict';

export const SETTING_SEARCH_HOUSE_FETCHED = 'SETTING_SEARCH_HOUSE_FETCHED';
export const SETTING_SEARCH_CLEARED = 'SETTING_SEARCH_CLEARED';
export const SETTING_SEARCH_KEYWORD_CHANGED = 'SETTING_SEARCH_KEYWORD_CHANGED';
