'use strict';

export const HOUSE_SIMILAR_FETCHED = 'HOUSE_SIMILAR_FETCHED';
export const HOUSE_BASE_FETCHED = 'HOUSE_BASE_FETCHED';
export const CALL_SELLER_FAILED = 'CALL_SELLER_FAILED';
export const ERROR_TIP_VISIBLE_CHANGED = 'ERROR_TIP_VISIBLE_CHANGED';
export const FEEDBACK_VISIBLE_CHANGED = 'FEEDBACK_VISIBLE_CHANGED';
export const SET_SELLER_PHONE = 'SET_SELLER_PHONE';
export const CLEAR_HOUSE_DETAIL_PAGE = 'CLEAR_HOUSE_DETAIL_PAGE';
export const HOSUE_CONTACT_LOG = 'HOSUE_CONTACT_LOG';
export const APPEND_HOUSE_CONTACT_LOG = 'APPEND_HOUSE_CONTACT_LOG';
export const CHANGE_CURRENT_CONTACT_LOG = 'CHANGE_CURRENT_CONTACT_LOG';
export const SET_WASH_ID = 'SET_WASH_ID';