'use strict';

export const HOUSE_SIMILAR_FETCHED = 'HOUSE_SIMILAR_FETCHED';
export const HOUSE_BASE_FETCHED = 'HOUSE_BASE_FETCHED';
export const HOUSE_STATUS_FETCHED = 'HOUSE_STATUS_FETCHED';
export const CALL_SELLER_SUCCESS = 'CALL_SELLER_SUCCESS';
export const CALL_SELLER_FAILED = 'CALL_SELLER_FAILED';
export const SCORE_TIP_VISIBLE_CHANGED = 'SCORE_TIP_VISIBLE_CHANGED';
export const ERROR_TIP_VISIBLE_CHANGED = 'ERROR_TIP_VISIBLE_CHANGED';
export const FEEDBACK_VISIBLE_CHANGED = 'FEEDBACK_VISIBLE_CHANGED';
export const SET_SELLER_PHONE = 'SET_SELLER_PHONE';
export const CLEAR_HOUSE_DETAIL_PAGE = 'CLEAR_HOUSE_DETAIL_PAGE';

