'use strict';

export const HOUSE_SIMILAR_FETCHED = 'HOUSE_SIMILAR_FETCHED';
export const HOUSE_BASE_FETCHED = 'HOUSE_BASE_FETCHED';
export const CALL_SELLER_FAILED = 'CALL_SELLER_FAILED';
export const ERROR_TIP_VISIBLE_CHANGED = 'ERROR_TIP_VISIBLE_CHANGED';
export const FEEDBACK_VISIBLE_CHANGED = 'FEEDBACK_VISIBLE_CHANGED';
export const SET_SELLER_PHONE = 'SET_SELLER_PHONE';
export const CLEAR_HOUSE_DETAIL_PAGE = 'CLEAR_HOUSE_DETAIL_PAGE';
export const HOSUE_CONTACT_LOG = 'HOSUE_CONTACT_LOG';
export const APPEND_HOUSE_CONTACT_LOG = 'APPEND_HOUSE_CONTACT_LOG';
export const CHANGE_CURRENT_CONTACT_LOG = 'CHANGE_CURRENT_CONTACT_LOG';

export const COUPON_VISIBLE_CHANGED = 'COUPON_VISIBLE_CHANGED';
export const SELLERPHONE_VISIBLE_CHANGED = 'SELLERPHONE_VISIBLE_CHANGED';

export const USER_INFO_FETCHED = 'USER_INFO_FETCHED';
export const COUPON_FETCHED = 'COUPON_FETCHED';
export const UPDATE_COUPON = 'UPDATE_COUPON';
export const SELLER_PHONE_FETCHED = 'SELLER_PHONE_FETCHED';

export const ENTER_STATUS_CHANGED = 'ENTER_STATUS_CHANGED';
export const VOICE_VISIBLE_CHANGED = 'VOICE_VISIBLE_CHANGED';
export const SET_ORDER_ID = 'SET_ORDER_ID';
export const UPDATE_PAYED_STATUS = 'UPDATE_PAYED_STATUS';
export const CALL_TIP_VISIBLE_CHANGED = 'CALL_TIP_VISIBLE_CHANGED';
export const PROPERTY_RECORD_FETCHED = 'PROPERTY_RECORD_FETCHED';