'use strict';

export const HOUSE_ATTENTION_FETCHED = 'HOUSE_ATTENTION_FETCHED';
export const HOUSE_ATTENTION_APPEND_FETCHED = 'HOUSE_ATTENTION_APPEND_FETCHED';
export const HOUSE_ATTENTION_PREPEND_FETCHED = 'HOUSE_ATTENTION_PREPEND_FETCHED';
export const ATTENTION_BLOCK_COMMUNITY_FETCHED = 'ATTENTION_BLOCK_COMMUNITY_FETCHED';
