'use strict';

export const HOUSE_ATTENTION_FETCHED = 'HOUSE_ATTENTION_FETCHED';
export const HOUSE_ATTENTION_APPEND_FETCHED = 'HOUSE_ATTENTION_APPEND_FETCHED';
export const HOUSE_ATTENTION_PREPEND_FETCHED = 'HOUSE_ATTENTION_PREPEND_FETCHED';
export const ATTENTION_BLOCK_COMMUNITY_FETCHED = 'ATTENTION_BLOCK_COMMUNITY_FETCHED';
export const CLEAR_HOME_PAGE = 'CLEAR_HOME_PAGE';
export const HOUSE_NEW_COUNT = 'HOUSE_NEW_COUNT';

export const SET_CONTACT_STATUS = 'SET_HOME_CONTACT_STATUS';
export const SET_LOOK_STATUS = 'SET_HOME_LOOK_STATUS';

export const SCORE_MODAL_VISIBLE_CHANGED = 'SCORE_MODAL_VISIBLE_CHANGED';
export const SCORE_MODAL_STATUS = 'SCORE_MODAL_STATUS';
export const COUPON_MODAL_VISIBLE_CHANGED = 'COUPON_MODAL_VISIBLE_CHANGED';
export const COUPON_MODAL_STATUS = 'COUPON_MODAL_STATUS';
export const RULE_MODAL_VISIBLE_CHANGED = 'RULE_MODAL_VISIBLE_CHANGED';
export const RULE_MODAL_STATUS = 'RULE_MODAL_STATUS';
export const RULE_MODAL_SHOW = 'RULE_MODAL_SHOW';
export const GIFT_MODAL_VISIBLE_CHANGED = 'GIFT_MODAL_VISIBLE_CHANGED';
export const GIFT_MODAL_STATUS = 'GIFT_MODAL_STATUS';
export const GIFT_MODAL_SHOW = 'GIFT_MODAL_SHOW';
export const HOUSE_CURRENT_STATUS = 'HOUSE_CURRENT_STATUS';

export const CURRENT_MODAL_CHANGED = 'CURRENT_MODAL_CHANGED';
export const PUSH_SHOW_MODAL = 'PUSH_SHOW_MODAL';
export const SCORE = 'SCORE_MODAL';
export const COUPON = 'COUPON_MODAL';
export const RULE = 'RULE_MODAL';
export const GIFT = 'GIFT_MODAL';
