'use strict';

export const HOUSE_FETCHED = 'HOUSE_FETCHED';
export const HOUSE_APPEND_FETCHED = 'HOUSE_APPEND_FETCHED';
export const HOUSE_PREPEND_FETCHED = 'HOUSE_PREPEND_FETCHED';
export const HOUSE_LIST_PAGE_CLEARED = 'HOUSE_LIST_PAGE_CLEARED';
export const HOUSE_FILTER_FETCHED = 'HOUSE_FILTER_FETCHED';
export const FILTER_ITEM_PRESSED = 'FILTER_ITEM_PRESSED';
export const ONLY_VERIFY_CHANGED = 'ONLY_VERIFY_CHANGED';
export const BLOCK_FILTER_CHANGED = 'BLOCK_FILTER_CHANGED';
export const FILTER_TAB_PRICE_CHANGED = 'FILTER_TAB_PRICE_CHANGED';
export const FILTER_TAB_BEDROOMS_CHANGED = 'FILTER_TAB_BEDROOMS_CHANGED';
export const AUTOCOMPLETE_VIEW_SHOWED = 'AUTOCOMPLETE_VIEW_SHOWED';
export const HOUSE_LIST_SEARCH_HOUSE_FETCHED = 'HOUSE_LIST_SEARCH_HOUSE_FETCHED';
export const HOUSE_LIST_SEARCH_KEYWORD_CHANGED = 'HOUSE_LIST_SEARCH_KEYWORD_CHANGED';
export const FILTER_COMMUNITY_NAME_CHANGED = 'FILTER_COMMUNITY_NAME_CHANGED';
export const FILTER_COMMUNITY_NAME_CLEARED = 'FILTER_COMMUNITY_NAME_CLEARED';

