'use strict';

export const BUILDING_CHANGED = 'BUILDING_CHANGED';
export const UNIT_CHANGED = 'UNIT_CHANGED';
export const DOOR_CHANGED = 'DOOR_CHANGED';
export const BEDROOMS_CHANGED = 'BEDROOMS_CHANGED';
export const LIVINGROOMS_CHANGED = 'LIVINGROOMS_CHANGED';
export const BATHROOMS_CHANGED = 'BATHROOMS_CHANGED';
export const AREA_CHANGED = 'AREA_CHANGED';
export const PRICE_CHANGED = 'PRICE_CHANGED';

export const ALIAS_CHANGED = 'ALIAS_CHANGED';
export const PHONE_CHANGED = 'PHONE_CHANGED';

export const SINGLE_CHANGED = 'SINGLE_CHANGED';
export const NO_UNIT_CHANGED = 'NO_UNIT_CHANGED';
export const VILLA_CHANGED = 'VILLA_CHANGED';
export const ERR_MSG = 'ERR_MSG';
