'use strict';

export const COMMUNITY_CHANGED = 'COMMUNITY_CHANGED';
export const BUILDING_CHANGED = 'BUILDING_CHANGED';
export const UNIT_CHANGED = 'UNIT_CHANGED';
export const DOOR_CHANGED = 'DOOR_CHANGED';
export const BEDROOMS_CHANGED = 'BEDROOMS_CHANGED';
export const LIVINGROOMS_CHANGED = 'LIVINGROOMS_CHANGED';
export const BATHROOMS_CHANGED = 'BATHROOMS_CHANGED';
export const AREA_CHANGED = 'AREA_CHANGED';
export const PRICE_CHANGED = 'PRICE_CHANGED';

export const ALIAS_CHANGED = 'ALIAS_CHANGED';
export const PHONE_CHANGED = 'PHONE_CHANGED';

export const ATTACH_BUILDING_CHANGED = 'ATTACH_BUILDING_CHANGED';
export const ATTACH_DOOR_CHANGED = 'ATTACH_DOOR_CHANGED';

export const SINGLE_CHANGED = 'SINGLE_CHANGED';
export const NO_UNIT_CHANGED = 'NO_UNIT_CHANGED';
export const VILLA_CHANGED = 'VILLA_CHANGED';
export const ERR_MSG = 'ERR_MSG';

export const INPUT_DATA_CLEARED = 'INPUT_DATA_CLEARED';

export const INPUT_BASE_CLEARED = 'INPUT_BASE_CLEARED';
export const INPUT_MORE_CLEARED = 'INPUT_MORE_CLEARED';
export const INPUT_LANDLORD_CLEARED = 'INPUT_LANDLORD_CLEARED';

/*搜索小区*/
export const HI_SEARCH_HOUSE_FETCHED = 'HI_SEARCH_HOUSE_FETCHED';
export const HI_SEARCH_CLEARED = 'HI_SEARCH_CLEARED';
export const HI_SEARCH_KEYWORD_CHANGED = 'HI_SEARCH_KEYWORD_CHANGED';