'use strict';

export const LIST_PUSH_ROUTE = 'LIST_PUSH_ROUTE';
export const DETAIL_PUSH_ROUTE = 'DETAIL_PUSH_ROUTE';
export const LIST_POP_ROUTE = 'LIST_POP_ROUTE';
export const DETAIL_POP_ROUTE = 'DETAIL_POP_ROUTE';

export const SET_CONTACT_STATUS = 'SET_CONTACT_STATUS';
export const SET_LOOK_STATUS = 'SET_LOOK_STATUS';