'use strict';

export const CONTACT_HOUSE_FETCHED = 'CONTACT_HOUSE_FETCHED';
export const INPUT_HOUSE_FETCHED = 'INPUT_HOUSE_FETCHED';
export const HOUSE_DATA_CLEARED = 'HOUSE_DATA_CLEARED';
export const CONTACT_HOUSE_PREPEND_FETCHED = 'CONTACT_HOUSE_PREPEND_FETCHED';
export const INPUT_HOUSE_PREPEND_FETCHED = 'INPUT_HOUSE_PREPEND_FETCHED';
export const TIME_APPLY_VISIBLE_CHANGED = 'TIME_APPLY_VISIBLE_CHANGED';
