'use strict';

export const USER_PROFILE = 'USER_PROFILE';

export const SCORE_LIST = 'SCORE_LIST';
export const SCORE_CLEARED = 'SCORE_CLEARED';
export const BIND_VISIBLE_CHANGED = 'BIND_VISIBLE_CHANGED';

//我的等级
export const EXP_RULE = 'EXP_RULE';

export const USER_INPUT_HOUSE_FETCHED = 'USER_INPUT_HOUSE_FETCHED';
export const USER_INPUT_HOUSE_CLEARED = 'USER_INPUT_HOUSE_CLEARED';

//签到
export const SIGN_IN_FETCHED = 'SIGN_IN_FETCHED';
export const SIGN_IN_VISIBLE_CHANGED = 'SIGN_IN_VISIBLE_CHANGED';
export const SIGN_IN_BUTTON_VISIBLE_CHANGED = 'SIGN_IN_BUTTON_VISIBLE_CHANGED';