export const ALIPAY_ACCOUNT_CHANGED = 'ALIPAY_ACCOUNT_CHANGED';
export const WITHDRAW_NAME_CHANGED = 'WITHDRAW_NAME_CHANGED';
export const WITHDRAW_PRICE_CHANGED = 'WITHDRAW_PRICE_CHANGED';
export const WITHDRAW_PRICE_CLEARED = 'WITHDRAW_PRICE_CLEARED';
export const WITHDRAW_ERR_MSG = 'WITHDRAW_ERR_MSG';
export const FROM_USER_FETCHED = 'FROM_USER_FETCHED';

export const BIND_STEP_CHANGED = 'BIND_STEP_CHANGED';
