export const ALIPAY_ACCOUNT_CHANGED = 'ALIPAY_ACCOUNT_CHANGED';
export const NAME_CHANGED = 'NAME_CHANGED';
export const PRICE_CHANGED = 'PRICE_CHANGED';
export const PRICE_CLEARED = 'PRICE_CLEARED';
export const ALIPAY_FETCHED = 'ALIPAY_FETCHED';
export const WITHDRAW_ERR_MSG = 'WITHDRAW_ERR_MSG';
export const MODAL_HIDDEN = 'MODAL_HIDDEN';
export const FROM_USER_FETCHED = 'FROM_USER_FETCHED';
